### ISSUE TITLE
Requesting more linear memory is broken

### ISSUE THREAD

**Issue by CryZe** [aduros/wasm4#30] opened 2021-08-28 16:33 UTC
If you request more linear memory, then the emulator's `this.memory` is not actually the one in use by the WASM instance anymore and the whole thing starts crashing and / or not displaying anything anymore.

Oh unless the idea is that allocating memory isn't even allowed. Though that doesn't seem to be enforced anywhere. For example Rust by default allocates 1MiB for the stack alone on startup, almost definitely true for C and C++ as well.

**Comment by tjpalmer** [comment] 2021-08-28 21:55
Yes, I think the idea is to limit it. I suspect doing this best will require an entirely new wasm engine rather than the ones built into browsers, but maybe there's some simpler solution.

**Comment by aduros** [comment] 2021-08-28 22:48
Hi! Yes, memory is fixed by design to 64 KB (one WebAssembly page).

The starter project templates for each language (including Rust and C) should have all the settings for running in low memory. Is something not working there?

**Comment by aduros** [comment] 2021-09-27 19:41
Requesting memory with heap allocation should work across all languages now, including Rust. Note that the max memory available to the system is still 64 KB. If there are still issues please reopen!

**Closed by aduros** 2021-09-27 19:41 UTC
