### ISSUE TITLE
APU parity

### ISSUE THREAD

**Issue by JerwuQu** [aduros/wasm4#321] opened 2022-01-14 04:06 UTC
Currently, the APU for web is implemented via methods in the Web Audio API. Aside from this causing slight differences between Chromium and Firefox, it also causes differences between native and web.

I think rewriting the web APU to be sample buffer-based like the native one would be a good idea. It would ensure that audio sounds exactly the same, and would make porting features between the two implementations much easier. I also suspect a sample-based implementation would make solving #308 easier.

Thoughts?

**Comment by kawa-yoiko** [comment] 2022-01-14 06:57
Yes, and I'd like to add that as Bruno mentioned "games that can be made to run 100 years from now", a sample-based implementation not only eases future porting work but also helps to preserve games. Relying on a high-level abstraction like Web Audio seems a bit less than enough — we have had lots of work put into soundcard emulations (SB16, 2A03, etc.), yet we are still unable to revive the delicate feel of many retro games out there. Even the pure-software PICO-8 APU is hard to accurately reproduce.

It seems less related to #308 though, as the problem there is more about synchronization (one audio tick lasts exactly from one `update` call to the next) for uninterrupted notes in music. The switch here might smooth the work, but in the end either the rules for audio ticks need to be revisited, or built-in sequencer should be introduced (#15).

**Comment by aduros** [comment] 2022-01-16 19:37
I committed an implementation for this on a branch. It seems to work ok, but there's one bug I found where there's popping at the beginning (and end?) of triangle tones. This can be reproduced in the sound demo by quickly repeating a low frequency triangle tone. It looks like it also affects the native APU a bit, but it's way more noticeable on web.

**Comment by JerwuQu** [comment] 2022-01-16 21:18
I'm assuming this only happens without attack/release? If so, it's because audio is snapping directly from a 0 sample to a (large) non-zero sample. Only way to reliably prevent is to hardcode a tiny-tiny attack and release, but that is probably not desirable for people that wish to continue their notes by reapplying them the next tick with another `tone` (which *in theory* should string them together without interruption).

**Closed** 2022-02-05 17:33 UTC
