### ISSUE TITLE
Flipped sprites are clipped incorrectly when going offscreen

### ISSUE THREAD

**Issue by Tinchetsu** [aduros/wasm4#350] opened 2022-01-21 19:48 UTC
Sprites with BLIT_FLIP_X flag clip incorrectly when going offscreen to the right

Here is my C code, one with a normal sprite, and another flipped.
`blit(witch2, player.x, player.y,      witch2Width, witch2Height, BLIT_2BPP);`
`blit(witch2, player.x, player.y + 20, witch2Width, witch2Height, BLIT_2BPP | BLIT_FLIP_X);`

It only happens when going offscreen to the right.

Attaching gif of the same sprites, one flipped
![game2](https://user-images.githubusercontent.com/10901731/150590802-bad5f3e6-226a-4a21-9e1a-0c4520b4ccf5.gif)

**Comment by JerwuQu** [comment] 2022-01-22 00:01
Seems like a duplicate of #11, which is fixed on the `main` branch already. Please try with [a recent artifact build](https://github.com/aduros/wasm4/suites/5015811086/artifacts/147508304) and see if it persists.

**Comment by Tinchetsu** [comment] 2022-01-22 19:15
I tested with the artifact buld, and it works. Thanks.

**Comment by aduros** [comment] 2022-01-23 14:02
Thanks for reporting this! A fix will be in the next release version.

**Closed by aduros** 2022-01-23 14:02 UTC
